### ISSUE TITLE
How to configure ansi color output

### ISSUE THREAD

**Issue by cmdjulian** [jstachio/rainbowgum#55]
I have the following logger: 

```kotlin
@AutoService(RainbowGumProvider::class)
class RainbowGumProviderImpl : RainbowGumProvider {
    override fun provide(config: LogConfig): Optional<RainbowGum> = RainbowGum.builder(config)
        .route { builder ->
            builder.level(Level.INFO)
            builder.appender("console") { appender ->
                val encoder = PatternEncoderBuilder("console")
                    .pattern("%cyan(%d{YYYY-MM-dd HH:mm:ss.SSS}) [%yellow(%thread)] %highlight(%-5level) %logger{36}: %msg%n")
                    .fromProperties(config.properties())
                    .build()

                appender.encoder(encoder)
                appender.output(LogOutput.ofStandardOut())
            }
        }
        .optional()
}
```

This is my gradle config:

```gradle
dependencies {
    ksp("dev.zacsweers.autoservice:auto-service-ksp:1.1.0")
    implementation("com.google.auto.service:auto-service-annotations:1.1.1")

    // logging
    implementation("io.jstach.rainbowgum:rainbowgum:0.2.0")
    implementation("io.jstach.rainbowgum:rainbowgum-core:0.2.0")
    implementation("io.jstach.rainbowgum:rainbowgum-pattern:0.2.0")
    implementation("io.jstach.rainbowgum:rainbowgum-jansi:0.2.0")
}
```

As you can see in my pattern I have configured colored output. Regardless of that the output is just white. Is there something I do wrong?

**Comment by cmdjulian** [comment]
Okay it seems like when compiling and using the jar as is, it works. Just in the IntelliJ terminal no colored output is provided

**Comment by agentgt** [comment]
Anyway I'm rolling out a new release very soon of 0.3.0. Hopefully the builder API didn't change too much that it breaks for you.

Once I hit 0.5.0 sometime this month the API will be more stable and by July hopefully 1.0.0

**Comment by agentgt** [comment]
Also see this bug: https://github.com/fusesource/jansi/issues/31

**Comment by agentgt** [comment]
@cmdjulian I can't load up intellij at the moment (yes I'm using Eclipse right now for null analysis but I do use Intellij from time to time).

In your application at boot up can you dump `System.getProperties()` to stdout. Don't paste it here but instead look for properties that look `intellij` specific like `jetbrains.loader` or something. Maybe System.getenv as well (absolutely do not paste the results of that here other than the jetbrains/intellij looking vars).

It may not set any but I'm hoping it might.

**Comment by cmdjulian** [comment]
> Also see this bug: [fusesource/jansi#31](https://github.com/fusesource/jansi/issues/31)

Oh, that's unfortunate 😞 

> Anyway I'm rolling out a new release very soon of 0.3.0. Hopefully the builder API didn't change too much that it breaks for you.
> 
> Once I hit 0.5.0 sometime this month the API will be more stable and by July hopefully 1.0.0

Cool, thanks for proving the lib! 😄  I integrated it into one of my OSS projects [whats-the-los](https://github.com/whats-the-loss/whats-the-loss) which is using GraalVM with native-image. Not a real benchmark, but I noticed using you lib in favor of using `logback` shaves of roughly 1ms from staring time in native image (considering a start time of 32ms its somewhat significant) and shrinks the resulting binary from roughly 90MB to 80MB (no stdlib xml stuff included anymore).

> In your application at boot up can you dump `System.getProperties()` to stdout. Don't paste it here but instead look for properties that look `intellij` specific like `jetbrains.loader` or something. Maybe System.getenv as well (absolutely do not paste the results of that here other than the jetbrains/intellij looking vars).

I checked but unfortunately there is no special property nor a certain env variable differentiating my default gnome terminal and the intellij one 😞 

PS: one small suggestion though, you may have noticed that I did include not just `core`, but also `pattern` explicitly, as having it pulled transitively by `gradle` does not make it accessible as `implementation` even if `io.jstach.rainbowgum:rainbowgum` is included as such. I think to have a better developer ergonomic, when including `io.jstach.rainbowgum:rainbowgum`, the transitive dependencies should be pulled in with the same scope so that having `implementation("io.jstach.rainbowgum:rainbowgum:0.2.0")` is enough. When just wanting to use the defaults, having `runtimeOnly("io.jstach.rainbowgum:rainbowgum:0.2.0")` should be sufficient.
