### ISSUE TITLE
`Throwable` methods don't log anything on `slf4j` binding

### ISSUE THREAD

**Issue by cmdjulian** [jstachio/rainbowgum#70]
Not quite sure why, but only the first log statement gets actually logged, the other two invocations don't print anything. Am I doing something wrong here?

```kotlin
private val logger = KotlinLogging.logger {}

fun main() {
    logger.info { "Hello, World!" }
    logger.error(IllegalArgumentException()) { "Hello, World!" }
    logger.error("Hello, World!", IllegalArgumentException())
}
```

It seems like this is for all logger methods which do include a `Throwable` in their signature. The logger faced I'm using on top of `Rainbowgum` is [kotlin-logging](https://github.com/oshai/kotlin-logging) which relies on `slf4j`. For other loggers like `logback` everything works as it should.

I created a small reproducer: [logger.zip](https://github.com/jstachio/rainbowgum/files/14628126/logger.zip)

**Comment by agentgt** [comment]
There were numerous bugs in 0.3.0 that I should have filed but instead just fixed. Let me check to see and will shortly get back to you.

**Comment by agentgt** [comment]
Confirmed. I know it worked at one point but apparently I recently broke it when I regenerated code and the unit test did not test the throwable (how embarrassing). The loggers are code generated.

I'm in the works of having a much more extensive testing suite.

**Comment by agentgt** [comment]
Pumping out a release now. I guess the static level loggers were not being tested for the throwable non marker calls.

**Comment by agentgt** [comment]
@cmdjulian 0.4.0 should be in Maven central (or at least it will be propagated shortly).

Thanks a ton for reporting this. By 0.5.0 we should be approaching less experimental and the API will stabilize as well.

**Comment by cmdjulian** [comment]
Thanks for `rainbowgum`! 👍🏻
